apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: malware-service
spec:
  releaseName: malware-service
  chart:
    spec:
      chart: service-deployment
      sourceRef:
        kind: HelmRepository
        name: harbor
    version: "0.0.1"
interval: 1m
install:
  remediation:
    retries: 3